[package]
name = "oldphotos-desktop"
version = "1.0.0"
description = "Old Photos Restorer â€” Desktop"
edition = "2021"

[lib]
name = "oldphotos_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "2"
